"""baseline

Revision ID: 55fea6a4c3ff
Revises:
Create Date: 2026-06-01 17:54:55.346920

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "55fea6a4c3ff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
