"""phase3 user activation columns

Revision ID: 974d78d0237a
Revises: d9138c17cb46
Create Date: 2026-06-04 09:58:33.359881

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974d78d0237a"
down_revision: str | Sequence[str] | None = "d9138c17cb46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("activation_token", sa.String(length=64), nullable=True))
    op.add_column(
        "users", sa.Column("activation_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_users_activation_token"), "users", ["activation_token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_activation_token"), table_name="users")
    op.drop_column("users", "activated_at")
    op.drop_column("users", "activation_expires_at")
    op.drop_column("users", "activation_token")
    # ### end Alembic commands ###
