"""phase5 supplier bills tables

Revision ID: af97ae35f9b5
Revises: 5fbbe7f31cc2
Create Date: 2026-06-05 10:36:33.777513

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af97ae35f9b5"
down_revision: str | Sequence[str] | None = "5fbbe7f31cc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier_bills",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ocr_engine", sa.String(length=32), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("bill_date", sa.Date(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("min_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_bills_tenant_id"), "supplier_bills", ["tenant_id"], unique=False
    )
    op.create_table(
        "supplier_bill_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_bill_id", sa.UUID(), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_bill_id"],
            ["supplier_bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_bill_events_supplier_bill_id"),
        "supplier_bill_events",
        ["supplier_bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_bill_events_tenant_id"),
        "supplier_bill_events",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "supplier_bill_lines",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_bill_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("name_ar", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("unit_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("line_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_bill_id"],
            ["supplier_bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_bill_lines_product_id"),
        "supplier_bill_lines",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_bill_lines_supplier_bill_id"),
        "supplier_bill_lines",
        ["supplier_bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_bill_lines_tenant_id"), "supplier_bill_lines", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_bill_lines_tenant_id"), table_name="supplier_bill_lines")
    op.drop_index(op.f("ix_supplier_bill_lines_supplier_bill_id"), table_name="supplier_bill_lines")
    op.drop_index(op.f("ix_supplier_bill_lines_product_id"), table_name="supplier_bill_lines")
    op.drop_table("supplier_bill_lines")
    op.drop_index(op.f("ix_supplier_bill_events_tenant_id"), table_name="supplier_bill_events")
    op.drop_index(
        op.f("ix_supplier_bill_events_supplier_bill_id"), table_name="supplier_bill_events"
    )
    op.drop_table("supplier_bill_events")
    op.drop_index(op.f("ix_supplier_bills_tenant_id"), table_name="supplier_bills")
    op.drop_table("supplier_bills")
    # ### end Alembic commands ###
