"""phase3 signup_requests

Revision ID: fcd870a131c0
Revises: 15039174f8b1
Create Date: 2026-06-03 22:03:39.031231

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcd870a131c0"
down_revision: str | Sequence[str] | None = "15039174f8b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signup_requests",
        sa.Column("business_name", sa.String(length=255), nullable=False),
        sa.Column("owner_phone", sa.String(length=32), nullable=False),
        sa.Column("owner_email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provisioned_tenant_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provisioned_tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signup_requests_owner_email"), "signup_requests", ["owner_email"], unique=False
    )
    op.create_index(op.f("ix_signup_requests_status"), "signup_requests", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signup_requests_status"), table_name="signup_requests")
    op.drop_index(op.f("ix_signup_requests_owner_email"), table_name="signup_requests")
    op.drop_table("signup_requests")
    # ### end Alembic commands ###
